"""
tests/test_vo_acl.py

VO ACL enforcement tests: verify that xrootd_require_vo restricts access
to specific paths based on VOMS VO membership embedded in the client's proxy
certificate.

Topology
--------
  nginx-xrootd VO server (port 11103)
    xrootd_root   /tmp/xrd-test/data
    xrootd_require_vo /cms   cms      # CMS VO required for /cms/
    xrootd_require_vo /atlas atlas    # ATLAS VO required for /atlas/
    # /public/ — no restriction

Proxy credentials (generated by the session fixture if absent)
--------------------------------------------------------------
  pki/user/proxy_cms.pem   — VOMS proxy: /cms/Role=NULL/Capability=NULL
  pki/user/proxy_atlas.pem — VOMS proxy: /atlas/Role=NULL/Capability=NULL
  pki/user/proxy_std.pem   — plain GSI proxy (no VOMS extension)

All proxies are signed by the local test CA and pass GSI authentication.
Only the VOMS-bearing proxies are admitted to their respective restricted
paths.

    pytest tests/test_vo_acl.py -v

Prerequisites
-------------
  - nginx binary at /tmp/nginx-1.28.3/objs/nginx (built with XROOTD_HAVE_VOMS)
  - Test PKI at /tmp/xrd-test/pki/  (CA, user cert+key, host cert+key)
  - voms-proxy-fake on PATH

The session fixture starts and stops its own nginx process on port 11103;
it does not touch the main test nginx on ports 11094/11095.
"""

import os
import json
import shutil
import subprocess
import sys
import tempfile
import time
from types import SimpleNamespace

import pytest
from XRootD import client
from XRootD.client.flags import OpenFlags, StatInfoFlags

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

NGINX_BIN   = "/tmp/nginx-1.28.3/objs/nginx"
PKI_DIR     = "/tmp/xrd-test/pki"
CA_DIR      = "/tmp/xrd-test/pki/ca"
VOMSDIR     = "/tmp/xrd-test/pki/vomsdir"
VOMS_CERT   = "/tmp/xrd-test/pki/voms/vomscert.pem"
VOMS_KEY    = "/tmp/xrd-test/pki/voms/vomskey.pem"
USER_CERT   = "/tmp/xrd-test/pki/user/usercert.pem"
USER_KEY    = "/tmp/xrd-test/pki/user/userkey.pem"
PROXY_STD   = "/tmp/xrd-test/pki/user/proxy_std.pem"
PROXY_CMS   = "/tmp/xrd-test/pki/user/proxy_cms.pem"
PROXY_ATLAS = "/tmp/xrd-test/pki/user/proxy_atlas.pem"
SERVER_CERT = "/tmp/xrd-test/pki/server/hostcert.pem"
SERVER_KEY  = "/tmp/xrd-test/pki/server/hostkey.pem"

DATA_ROOT   = "/tmp/xrd-test/data"
VO_PORT     = 11103
VO_URL      = f"root://localhost:{VO_PORT}"

VO_NGINX_DIR = "/tmp/xrd-vo-test"

# Resolve voms-proxy-fake: prefer Python script in utils/, fall back to system binary
_UTILS_DIR = os.path.join(os.path.dirname(__file__), "..", "utils")
_VOMS_PROXY_FAKE_PY = os.path.join(_UTILS_DIR, "voms_proxy_fake.py")
if os.path.isfile(_VOMS_PROXY_FAKE_PY):
    VOMS_PROXY_FAKE = [sys.executable, _VOMS_PROXY_FAKE_PY]
elif shutil.which("voms-proxy-fake"):
    VOMS_PROXY_FAKE = ["voms-proxy-fake"]
else:
    VOMS_PROXY_FAKE = None


# ---------------------------------------------------------------------------
# VOMS infrastructure helpers
# ---------------------------------------------------------------------------

def _voms_dn(pem: str, field: str) -> str:
    """Return subject or issuer DN from a PEM cert in OpenSSL one-line format."""
    r = subprocess.run(
        ["openssl", "x509", "-in", pem, "-noout", f"-{field}", "-nameopt", "compat"],
        check=True, capture_output=True, text=True,
    )
    # Output: "subject= /DC=..." or "issuer= /DC=..."
    return r.stdout.strip().split("=", 1)[1].strip()


def _make_voms_signing_cert():
    """
    Create a VOMS signing key + cert signed by the test CA, with
    SubjectKeyIdentifier so that voms-proxy-fake can embed an AKI in the AC.
    """
    os.makedirs(os.path.dirname(VOMS_CERT), exist_ok=True)

    if os.path.exists(VOMS_CERT) and os.path.exists(VOMS_KEY):
        return  # already exists

    # Generate key
    subprocess.run(
        ["openssl", "genrsa", "-out", VOMS_KEY, "2048"],
        check=True, capture_output=True,
    )

    # CSR
    csr = VOMS_CERT.replace(".pem", ".csr")
    subprocess.run(
        ["openssl", "req", "-new",
         "-key", VOMS_KEY,
         "-subj", "/DC=test/DC=xrootd/CN=voms.test.local",
         "-out", csr],
        check=True, capture_output=True,
    )

    # ext config
    ext_file = VOMS_CERT.replace(".pem", "_ext.conf")
    with open(ext_file, "w") as f:
        f.write("[voms_ext]\n"
                "subjectKeyIdentifier = hash\n"
                "authorityKeyIdentifier = keyid:always\n"
                "basicConstraints = CA:FALSE\n")

    # Sign with test CA
    subprocess.run(
        ["openssl", "x509", "-req",
         "-in", csr,
         "-CA", f"{CA_DIR}/ca.pem",
         "-CAkey", f"{CA_DIR}/ca.key",
         "-CAcreateserial",
         "-out", VOMS_CERT,
         "-days", "365",
         "-extensions", "voms_ext",
         "-extfile", ext_file],
        check=True, capture_output=True,
    )


def _make_vomsdir():
    """
    Create a vomsdir with LSC files for the 'cms' and 'atlas' VOs, both
    pointing at the local VOMS signing cert.
    """
    subject = _voms_dn(VOMS_CERT, "subject")
    issuer  = _voms_dn(VOMS_CERT, "issuer")
    lsc_content = f"{subject}\n{issuer}\n"

    for vo in ("cms", "atlas"):
        vo_dir = os.path.join(VOMSDIR, vo)
        os.makedirs(vo_dir, exist_ok=True)
        lsc = os.path.join(vo_dir, "voms.test.local.lsc")
        with open(lsc, "w") as f:
            f.write(lsc_content)


def _make_voms_proxy(vo: str, fqan: str, out: str):
    """Create a fake VOMS proxy for *vo* with the given *fqan*."""
    subprocess.run(
        VOMS_PROXY_FAKE + [
         "-cert",     USER_CERT,
         "-key",      USER_KEY,
         "-certdir",  CA_DIR,
         "-hostcert", VOMS_CERT,
         "-hostkey",  VOMS_KEY,
         "-voms",     vo,
         "-fqan",     fqan,
         "-uri",      "voms.test.local:15000",
         "-out",      out,
         "-hours",    "24"],
        check=True, capture_output=True,
    )


def _proxy_is_valid(path: str) -> bool:
    """Return True if the proxy file exists and is not yet expired."""
    if not os.path.exists(path):
        return False
    r = subprocess.run(
        ["openssl", "x509", "-in", path, "-noout", "-checkend", "3600"],
        capture_output=True,
    )
    return r.returncode == 0


# ---------------------------------------------------------------------------
# nginx VO server helpers
# ---------------------------------------------------------------------------

_VO_NGINX_CONF = """\
daemon off;
worker_processes 1;
error_log {log_dir}/error.log info;
pid       {log_dir}/nginx.pid;

thread_pool default threads=4 max_queue=65536;
events {{ worker_connections 64; }}

stream {{
    server {{
        listen {port};
        xrootd on;
        xrootd_root {data_root};
        xrootd_auth gsi;
        xrootd_allow_write on;
        xrootd_certificate     {server_cert};
        xrootd_certificate_key {server_key};
        xrootd_trusted_ca      {ca_dir}/ca.pem;
        xrootd_vomsdir         {vomsdir};
        xrootd_voms_cert_dir   {ca_dir};
        xrootd_require_vo /cms   cms;
        xrootd_require_vo /atlas atlas;
        xrootd_access_log {log_dir}/xrootd_access.log;
    }}
}}
"""


def _write_vo_nginx_conf(conf_path: str):
    log_dir = os.path.join(VO_NGINX_DIR, "logs")
    os.makedirs(log_dir, exist_ok=True)
    content = _VO_NGINX_CONF.format(
        port=VO_PORT,
        data_root=DATA_ROOT,
        server_cert=SERVER_CERT,
        server_key=SERVER_KEY,
        ca_dir=CA_DIR,
        vomsdir=VOMSDIR,
        log_dir=log_dir,
    )
    with open(conf_path, "w") as f:
        f.write(content)


def _start_vo_nginx(conf_path: str) -> subprocess.Popen:
    log_dir = os.path.join(VO_NGINX_DIR, "logs")
    stderr_path = os.path.join(log_dir, "startup_stderr.log")
    stderr_fh = open(stderr_path, "w")
    proc = subprocess.Popen(
        [NGINX_BIN, "-c", conf_path],
        stdout=subprocess.DEVNULL,
        stderr=stderr_fh,
    )

    # With daemon off, nginx stays in the foreground.  Give it a moment to
    # start (or fail with a config error).
    time.sleep(1.0)
    if proc.poll() is not None:
        stderr_fh.close()
        with open(stderr_path) as f:
            stderr_text = f.read()
        if "libvomsapi" in stderr_text:
            pytest.skip(
                "libvomsapi.so.1 not available — "
                "skipping VO ACL tests"
            )
        pytest.fail(
            f"VO nginx exited immediately (rc={proc.returncode}).\n"
            f"stderr: {stderr_text}"
        )

    # Wait up to 10 s for the port to accept authenticated connections
    for _ in range(20):
        # Make sure process is still alive
        if proc.poll() is not None:
            stderr_fh.close()
            with open(stderr_path) as f:
                stderr_text = f.read()
            pytest.fail(
                f"VO nginx exited (rc={proc.returncode}) during startup.\n"
                f"stderr: {stderr_text}"
            )
        r = subprocess.run(
            ["xrdfs", VO_URL, "ls", "/"],
            env={**os.environ,
                 "X509_CERT_DIR":   CA_DIR,
                 "X509_USER_PROXY": PROXY_CMS,
                 "XrdSecPROTOCOL":  "gsi"},
            capture_output=True, timeout=5,
        )
        if r.returncode == 0:
            return proc
        time.sleep(0.5)
    proc.terminate()
    pytest.fail(
        f"VO nginx server did not become ready on port {VO_PORT}.\n"
        f"Check {VO_NGINX_DIR}/logs/error.log"
    )


# ---------------------------------------------------------------------------
# Session fixture: build VOMS infra + start VO nginx
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session", autouse=True)
def vo_nginx(tmp_path_factory):
    """
    Build the VOMS test infrastructure (signing cert, vomsdir, proxies) and
    start a dedicated nginx on VO_PORT with xrootd_require_vo restrictions.

    Skips the whole module if voms-proxy-fake is not on PATH or the nginx
    binary is absent.
    """
    if not VOMS_PROXY_FAKE:
        pytest.skip("voms-proxy-fake not found — skipping VO ACL tests")
    if not os.path.exists(NGINX_BIN):
        pytest.skip(
            f"nginx binary not found at {NGINX_BIN} — "
            "build with: cd /tmp/nginx-1.28.3 && make -j$(nproc)"
        )

    # ---- VOMS signing cert
    _make_voms_signing_cert()

    # ---- vomsdir (LSC files)
    _make_vomsdir()

    # ---- Plain GSI proxy (recreate if expired or absent)
    if not _proxy_is_valid(PROXY_STD):
        subprocess.run(
            ["python3", os.path.join(os.path.dirname(__file__), "..", "utils", "make_proxy.py")],
            check=True, capture_output=True,
        )

    # ---- VOMS proxies (recreate if expired or absent)
    if not _proxy_is_valid(PROXY_CMS):
        _make_voms_proxy("cms",   "/cms/Role=NULL/Capability=NULL",   PROXY_CMS)
    if not _proxy_is_valid(PROXY_ATLAS):
        _make_voms_proxy("atlas", "/atlas/Role=NULL/Capability=NULL", PROXY_ATLAS)

    # ---- Test data directories
    for subdir in ("cms", "atlas", "public"):
        path = os.path.join(DATA_ROOT, subdir)
        os.makedirs(path, exist_ok=True)
        # Seed a readable file in each directory
        seed = os.path.join(path, "seed.txt")
        if not os.path.exists(seed):
            with open(seed, "w") as f:
                f.write(f"seed file for {subdir}\n")

    # ---- Start VO nginx
    os.makedirs(VO_NGINX_DIR, exist_ok=True)
    conf_path = os.path.join(VO_NGINX_DIR, "nginx.conf")
    _write_vo_nginx_conf(conf_path)
    proc = _start_vo_nginx(conf_path)

    yield proc

    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _gsi_env(proxy: str) -> dict:
    env = os.environ.copy()
    env["X509_CERT_DIR"]   = CA_DIR
    env["X509_USER_PROXY"] = proxy
    env["XrdSecPROTOCOL"]  = "gsi"
    env.pop("X509_USER_CERT", None)
    env.pop("X509_USER_KEY",  None)
    return env


def _xrdfs_stat(path: str, proxy: str) -> int:
    """Return exit code of xrdfs stat on the VO server."""
    r = subprocess.run(
        ["xrdfs", VO_URL, "stat", path],
        env=_gsi_env(proxy), capture_output=True, timeout=10,
    )
    return r.returncode


def _xrdfs_ls(path: str, proxy: str) -> int:
    """Return exit code of xrdfs ls on the VO server."""
    r = subprocess.run(
        ["xrdfs", VO_URL, "ls", path],
        env=_gsi_env(proxy), capture_output=True, timeout=10,
    )
    return r.returncode


def _xrdcp_read(remote: str, proxy: str) -> int:
    """Download remote path to a temp file and return xrdcp exit code."""
    fd, tmp = tempfile.mkstemp()
    os.close(fd)
    try:
        r = subprocess.run(
            ["xrdcp", "-f", "-s", f"{VO_URL}/{remote}", tmp],
            env=_gsi_env(proxy), capture_output=True, timeout=15,
        )
        return r.returncode
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def _xrdcp_write(content: bytes, remote: str, proxy: str) -> int:
    """Upload *content* to remote path and return xrdcp exit code."""
    fd, tmp = tempfile.mkstemp()
    os.write(fd, content)
    os.close(fd)
    try:
        r = subprocess.run(
            ["xrdcp", "-f", "-s", tmp, f"{VO_URL}/{remote}"],
            env=_gsi_env(proxy), capture_output=True, timeout=15,
        )
        return r.returncode
    finally:
        os.unlink(tmp)


def _python_stat(path: str, proxy: str):
    """
    Return (status, stat_info) using the Python XRootD client.

    The XRootD client library caches credential state inside the process.  Run
    this small probe in a fresh interpreter so switching between VOMS proxies in
    the full pytest session uses the intended credential.
    """
    code = """
import json
import sys
from XRootD import client

fs = client.FileSystem(sys.argv[1])
status, _ = fs.stat(sys.argv[2])
print(json.dumps({"ok": bool(status.ok), "message": status.message}))
"""
    r = subprocess.run(
        [sys.executable, "-c", code, VO_URL, path],
        env=_gsi_env(proxy),
        capture_output=True,
        text=True,
        timeout=15,
    )
    if r.returncode != 0:
        message = (r.stderr or r.stdout).strip() or f"python stat exited {r.returncode}"
        return SimpleNamespace(ok=False, message=message), None

    payload = json.loads(r.stdout.strip().splitlines()[-1])
    return SimpleNamespace(ok=payload["ok"], message=payload["message"]), None


# ---------------------------------------------------------------------------
# Tests: CMS proxy → /cms/ (allowed) and /atlas/ (denied)
# ---------------------------------------------------------------------------

class TestCmsProxy:
    """A VOMS proxy carrying the 'cms' VO is admitted to /cms/ and denied /atlas/."""

    def test_stat_cms_dir(self, vo_nginx):
        """CMS proxy can stat the /cms/ directory."""
        assert _xrdfs_stat("/cms", PROXY_CMS) == 0

    def test_dirlist_cms(self, vo_nginx):
        """CMS proxy can list the /cms/ directory."""
        assert _xrdfs_ls("/cms", PROXY_CMS) == 0

    def test_read_cms_file(self, vo_nginx):
        """CMS proxy can read a file in /cms/."""
        assert _xrdcp_read("/cms/seed.txt", PROXY_CMS) == 0

    def test_write_cms_file(self, vo_nginx):
        """CMS proxy can write a file into /cms/."""
        assert _xrdcp_write(b"cms write test\n", "/cms/cms_write.txt", PROXY_CMS) == 0

    def test_stat_cms_file_python_client(self, vo_nginx):
        """Python XRootD client: CMS proxy stat returns ok for a /cms/ path."""
        status, _ = _python_stat("/cms/seed.txt", PROXY_CMS)
        assert status.ok, f"stat /cms/seed.txt with cms proxy failed: {status.message}"

    def test_denied_atlas_stat(self, vo_nginx):
        """CMS proxy must NOT stat /atlas/."""
        assert _xrdfs_stat("/atlas", PROXY_CMS) != 0

    def test_denied_atlas_read(self, vo_nginx):
        """CMS proxy must NOT read from /atlas/."""
        assert _xrdcp_read("/atlas/seed.txt", PROXY_CMS) != 0

    def test_denied_atlas_write(self, vo_nginx):
        """CMS proxy must NOT write to /atlas/."""
        assert _xrdcp_write(b"should not land\n", "/atlas/cms_intruder.txt",
                            PROXY_CMS) != 0

    def test_denied_atlas_python_client(self, vo_nginx):
        """Python XRootD client: CMS proxy stat of /atlas/ returns not-ok."""
        status, _ = _python_stat("/atlas/seed.txt", PROXY_CMS)
        assert not status.ok, "CMS proxy should be denied /atlas/ path"


# ---------------------------------------------------------------------------
# Tests: ATLAS proxy → /atlas/ (allowed) and /cms/ (denied)
# ---------------------------------------------------------------------------

class TestAtlasProxy:
    """A VOMS proxy carrying the 'atlas' VO is admitted to /atlas/ and denied /cms/."""

    def test_stat_atlas_dir(self, vo_nginx):
        """ATLAS proxy can stat the /atlas/ directory."""
        assert _xrdfs_stat("/atlas", PROXY_ATLAS) == 0

    def test_dirlist_atlas(self, vo_nginx):
        """ATLAS proxy can list the /atlas/ directory."""
        assert _xrdfs_ls("/atlas", PROXY_ATLAS) == 0

    def test_read_atlas_file(self, vo_nginx):
        """ATLAS proxy can read a file in /atlas/."""
        assert _xrdcp_read("/atlas/seed.txt", PROXY_ATLAS) == 0

    def test_write_atlas_file(self, vo_nginx):
        """ATLAS proxy can write a file into /atlas/."""
        assert _xrdcp_write(b"atlas write test\n", "/atlas/atlas_write.txt",
                            PROXY_ATLAS) == 0

    def test_denied_cms_stat(self, vo_nginx):
        """ATLAS proxy must NOT stat /cms/."""
        assert _xrdfs_stat("/cms", PROXY_ATLAS) != 0

    def test_denied_cms_read(self, vo_nginx):
        """ATLAS proxy must NOT read from /cms/."""
        assert _xrdcp_read("/cms/seed.txt", PROXY_ATLAS) != 0

    def test_denied_cms_write(self, vo_nginx):
        """ATLAS proxy must NOT write to /cms/."""
        assert _xrdcp_write(b"should not land\n", "/cms/atlas_intruder.txt",
                            PROXY_ATLAS) != 0


# ---------------------------------------------------------------------------
# Tests: plain GSI proxy (no VOMS) → denied all restricted paths
# ---------------------------------------------------------------------------

class TestPlainProxy:
    """
    A plain GSI proxy (no VOMS extension) authenticates successfully but
    carries no VO membership, so it must be denied every VO-restricted path.
    """

    def test_denied_cms_stat(self, vo_nginx):
        """Plain proxy denied stat on /cms/."""
        assert _xrdfs_stat("/cms", PROXY_STD) != 0

    def test_denied_cms_read(self, vo_nginx):
        """Plain proxy denied read from /cms/."""
        assert _xrdcp_read("/cms/seed.txt", PROXY_STD) != 0

    def test_denied_atlas_stat(self, vo_nginx):
        """Plain proxy denied stat on /atlas/."""
        assert _xrdfs_stat("/atlas", PROXY_STD) != 0

    def test_denied_atlas_read(self, vo_nginx):
        """Plain proxy denied read from /atlas/."""
        assert _xrdcp_read("/atlas/seed.txt", PROXY_STD) != 0

    def test_allowed_public_stat(self, vo_nginx):
        """Plain proxy is allowed to stat the unrestricted /public/ directory."""
        assert _xrdfs_stat("/public", PROXY_STD) == 0

    def test_allowed_public_read(self, vo_nginx):
        """Plain proxy can read a file in the unrestricted /public/ directory."""
        assert _xrdcp_read("/public/seed.txt", PROXY_STD) == 0


# ---------------------------------------------------------------------------
# Tests: unrestricted /public/ is accessible to all VOs
# ---------------------------------------------------------------------------

class TestPublicAccess:
    """Any authenticated client can access paths without a VO restriction."""

    def test_cms_proxy_public_stat(self, vo_nginx):
        assert _xrdfs_stat("/public", PROXY_CMS) == 0

    def test_atlas_proxy_public_stat(self, vo_nginx):
        assert _xrdfs_stat("/public", PROXY_ATLAS) == 0

    def test_cms_proxy_public_read(self, vo_nginx):
        assert _xrdcp_read("/public/seed.txt", PROXY_CMS) == 0

    def test_atlas_proxy_public_read(self, vo_nginx):
        assert _xrdcp_read("/public/seed.txt", PROXY_ATLAS) == 0

    def test_cms_proxy_public_write(self, vo_nginx):
        assert _xrdcp_write(b"public write by cms\n",
                            "/public/cms_public.txt", PROXY_CMS) == 0

    def test_atlas_proxy_public_write(self, vo_nginx):
        assert _xrdcp_write(b"public write by atlas\n",
                            "/public/atlas_public.txt", PROXY_ATLAS) == 0
